<?php

namespace AppBundle\Repository;

/**
 * CategroyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategroyRepository extends \Doctrine\ORM\EntityRepository
{
}
