<?php

namespace AppBundle\Repository;

/**
 * TblProductCategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TblProductCategoryRepository extends \Doctrine\ORM\EntityRepository
{
}
