AppBundle\Entity\Categroy:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\CategroyRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
        description:
            type: string
            length: 255
        parentId:
            type: integer
            column: parent_id
        createdAt:
            type: datetime
            column: created_at
        updatedAt:
            type: datetime
            column: updated_at
    oneToMany:
        child:
            targetEntity: Categroy
            mappedBy: category_id
    lifecycleCallbacks: {  }
